[package]
name = "types"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
bitcode = "0.6.9"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
thiserror = "2.0.17"
tracing = "0.1.41"
