[package]
name = "tauri-invoke-proc"
version = "0.1.0"
edition = "2021"

[dependencies]
ctor = "0.6.0"
lazy_static = "1.5.0"
once_cell = "1.21.3"
proc-macro2 = "1.0.103"
quote = "1.0.41"
regex = "1.12.2"
serde = "1.0.228"
serde_json = "1.0.145"
syn = "2.0.108"
tracing = "0.1.41"

[lib]
proc-macro = true
