[package]
name = "tauri-invoke-proc"
version = "0.1.0"
edition = "2021"

[dependencies]
ctor = "0.4.0"
lazy_static = "1.5.0"
once_cell = "1.20.3"
proc-macro2 = "1.0.94"
quote = "1.0.39"
regex = "1.11.1"
serde = "1.0.218"
serde_json = "1.0.140"
syn = "2.0.99"
tracing = "0.1.41"

[lib]
proc-macro = true
