[package]
name = "lyrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.5"
reqwest = "0.12.4"
scraper = "0.19.0"
serde = "1.0.203"
serde_json = "1.0.117"
tokio = "1.38.0"
types = { path = "../types" }
librespot = { path = "../librespot" }
